# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

include_guard(DIRECTORY)

function(llm_lib2n_print_project_summary)
    message(STATUS "")
    message(STATUS "******************** Summary ********************")
    message(STATUS "  CMake Version                      : ${CMAKE_VERSION}")
    message(STATUS "  CMake Command                      : ${CMAKE_COMMAND}")
    message(STATUS "  System                             : ${CMAKE_SYSTEM_NAME}")
    message(STATUS "  C++ Compiler                       : ${CMAKE_CXX_COMPILER}")
    message(STATUS "  C++ Compiler Version               : ${CMAKE_CXX_COMPILER_VERSION}")
    message(STATUS "  Python Version                     : ${Python3_VERSION}")
    message(STATUS "  Python Interpreter                 : ${Python3_EXECUTABLE}")
    message(STATUS "  Torch Version                      : ${TORCH_VERSION}")
    message(STATUS "  Torch Library                      : ${TORCH_LIBRARY}")
    message(STATUS "  Build Type                         : ${CMAKE_BUILD_TYPE}")
    message(STATUS "")
    message(STATUS "  PROJECT_VERSION                    : ${PROJECT_VERSION}")
    message(STATUS "  llm_lib2N_BUILD_FOR_NATIVE         : ${llm_lib2N_BUILD_FOR_NATIVE}")
    message(STATUS "  llm_lib2N_INSTALL_STANDALONE       : ${llm_lib2N_INSTALL_STANDALONE}")
    message(STATUS "  llm_lib2N_PERFORM_LTO              : ${llm_lib2N_PERFORM_LTO}")
    message(STATUS "  llm_lib2N_RUN_CLANG_TIDY           : ${llm_lib2N_RUN_CLANG_TIDY}")
    if(llm_lib2N_RUN_CLANG_TIDY)
        message(STATUS "    clang-tidy                       : ${CLANG_TIDY_EXECUTABLE}")
    endif()
    if(NOT llm_lib2N_SANITIZERS OR llm_lib2N_SANITIZERS STREQUAL "nosan")
        message(STATUS "  llm_lib2N_SANITIZERS               : -")
    else()
        message(STATUS "  llm_lib2N_SANITIZERS               : ${llm_lib2N_SANITIZERS}")
    endif()
    message(STATUS "  llm_lib2N_TREAT_WARNINGS_AS_ERRORS : ${llm_lib2N_TREAT_WARNINGS_AS_ERRORS}")
    message(STATUS "  llm_lib2N_SUPPORT_IMAGE            : ${llm_lib2N_SUPPORT_IMAGE}")
    message(STATUS "  llm_lib2N_USE_LIBTORCH             : ${llm_lib2N_USE_LIBTORCH}")
    message(STATUS "  llm_lib2N_USE_CUDA                 : ${llm_lib2N_USE_CUDA}")
    if(llm_lib2N_USE_CUDA)
        message(STATUS "    CUDA Version                     : ${CUDAToolkit_VERSION}")
        message(STATUS "    CUDA NVCC                        : ${CUDAToolkit_NVCC_EXECUTABLE}")
        message(STATUS "    CUDA Architectures               : ${CMAKE_CUDA_ARCHITECTURES}")
    endif()
    message(STATUS "  llm_lib2N_BUILD_PYTHON_BINDINGS    : ${llm_lib2N_BUILD_PYTHON_BINDINGS}")
    if(llm_lib2N_BUILD_PYTHON_BINDINGS)
        message(STATUS "  llm_lib2N_PYTHON_DEVEL             : ${llm_lib2N_PYTHON_DEVEL}")
    endif()
    message(STATUS "")
    message(STATUS "  System Dependencies")
    if(llm_lib2N_THREAD_LIB STREQUAL "tbb")
        message(STATUS "    Intel oneTBB                     : ${TBB_VERSION}")
    endif()
    message(STATUS "    libsndfile                       : ${SndFile_VERSION}")
    message(STATUS "")
endfunction()
